### ISSUE TITLE
Question re: handling sessions

### ISSUE THREAD

**Issue by brainshower** [signalpoint/jDrupal#14]
From the current documentation, I am having trouble understanding how sessions are handled.  Once a user is logged in via user_login(), how do I pass the session information via all subsequent jDrupal calls?  Right now, calling node_save() in my JS app causes Drupal to produce the following return:

"403 (: Access denied for user anonymous)"

I believe this is because the session info is not being sent, but from the docs & code I cannot see where node_save() uses the session from a previous user_login.

**Comment by signalpoint** [comment]
@brainshower Before calling `node_save()`, if you do an `alert(Drupal.user.uid);`, what value is shown?

jDrupal handles sessions and tokens automatically once you are logged in.

**Comment by brainshower** [comment]
Thanks for the quick reply.  To answer your question, it is "0".

However, I should probably give you some additional information.  I am wrapping jDrupal in [Ionic](http://ionicframework.com/) as an Angular Service.  I am trying to figure out what to do with the system_connect() call, and if that is the culprit.  Should all jDrupal functions occur within a single system_connect "success" callback closure?  Or, should I call system_connect() just prior to every jDrupal call?

**Comment by signalpoint** [comment]
@brainshower Thanks for clarifying. So we can see the system thinks the user is anonymous at the time of the node_save() call, interesting...

You'll typically only need to call the system_connect() once when your app loads, and that'll initiate the session with your Drupal site, and return to you session and user information via JSON.

When you call user_login(), its success handler makes another call to system_connect() to fetch the new session and user info: https://github.com/easystreet3/jDrupal/blob/7.x-1.x/src/services/services.user.js#L104, and it does set the new Drupal user object aside in the global `Drupal.user` variable.

All subsequent jDrupal calls do not need to be proceeded by a system_connect() call.

I haven't given Angular or Ionic a try yet, but I'm curious to learn more. If all else fails, be sure to clear your browser's cache once in a while.

FYI, soon we'll be replacing the global `Drupal` object with `jDrupal`, so in the future the jDrupal user will be available at `jDrupal.user`. So hopefully the current global `Drupal` object isn't colliding with other Drupal related code you may have.

Either way, something is happening with your session along the way. Try turning on the debug mode under admin/structure services, and check out watchdog for more clues.

**Comment by ustange** [comment]
Drupal authenticates users with Cookies, thus _when running on a domain that is different from Drupal's_ Angular's `$http` (or sth. else like `Restangular`) needs to send a Cookie-Header like this: `Cookie: Session-Name=Session-ID`. For this to work the server must set the header `Access-Control-Allow-Credentials: true`, which requires the `Access-Control-Allow-Origin` header to be set, _but not equal to `*`_ – the problem now is: an app running natively on a device has no origin-URL that could be used for `Access-Control-Allow-Origin`, and therefore the whole auth-flow is broken (see [this ionic blog post](http://ionicframework.com/blog/angularjs-authentication/) for more information, also note [this comment](http://ionicframework.com/blog/angularjs-authentication/#comment-1592077366)).

So:

@brainshower 
- Can you exclude CORS issues like the one I just described?

@signalpoint
- How does jDrupal handle user-authentication? I can't tell from a quick look at the code. Especially: does it rely on Cookies?

**Comment by signalpoint** [comment]
@ustange It does rely on cookies, so it does not send along cookie/session info in the header. I'm interested in accommodating Angular, so please let me know what needs to be done to help out, thanks.

**Comment by rjcorwin** [comment]
The "uid is 0" issue seems to happen only when the JS running is on a different domain than Drupal. Because `services.request.call` is making an HTTP request with an instanceXMLHttpRequest object where the `withCredential` is not set to `true`, it would make sense that `system_connect` would return the anonymous user because without `withCredential` set to true, cookies are not sent along to the remote Drupal instance thus Drupal thinks the browser is an anonymous user (where UID is always 0). 

Setting `withCredentials: true` [here](https://github.com/easystreet3/jDrupal/blob/7.x-1.x/src/services/services.js#L25) and [here](https://github.com/easystreet3/jDrupal/blob/7.x-1.x/src/services/services.js#L224), it seems to be working for me. It doesn't make sense to have this set in all cases though. @signalpoint What would be a good way to set this property on a case by case basis given the patterns you are following? Backbone.js for example follows this pattern of hooking into the beginning of every request:

``` js
    // Place the Backbone.sync method off to the side before we write over it.
    var originalSync = Backbone.sync
    // Write over the Backbone sync method with our custom function.
    Backbone.sync = function(method, model, options) {
      options || (options = {})
      options.crossDomain = true
      options.xhrFields = {withCredentials:true};
      // Now feed those variables we set into the original sync method.
      return originalSync(method, model, options)
    }
```

**Comment by signalpoint** [comment]
@rjsteinert It looks like we'll need another hook, e.g. `hook_XMLHttpRequest()` invoked like so before the request object is made:

```
module_invoke_all('XMLHttpRequest', options);
```

Then I'd suggest the implentor use something like this (within a custom jDrupal module):

```
function my_module_XMLHttpRequest(options) {
  if (options.service == 'user' && options.resource == 'login') {
    options.XMLHttpRequest = new XMLHttpRequest(/* insert custom stuff here */);
  }
}
```

Then back in jDrupal, we'd check to see if anyone populated `options.XMLHttpRequest` and use it if they did, otherwise just create an empty request object. Thoughts?

**Comment by mcchrome** [comment]
I'm also trying to get Ionic working with jDrupal. Anything new on this issue? Btw I think jDrupal is totally fantastic so I'd love to get the authentication to work.

**Comment by signalpoint** [comment]
@mcchrome Thank you for the kind words. jDrupal user login/logout is stable in both Drupal 7 and 8. I'm going to close this issue for now since it is quite old and contains a wide range of topics. If you're still having an issue, please create a new issue with environment specifics/debugs/errors/screenshots/etc
