### ISSUE TITLE
Register jDrupal on Bower?

### ISSUE THREAD

**Issue by rjcorwin** [signalpoint/jDrupal#23]
Hi @easystreet3 - Would you mind listing jDrupal on Bower? I would prefer to reference jDrupal as a dependency in my `bower.json` file as opposed to checking it into my codebase. Directions on registering jDrupal as a package on Bower [here](http://bower.io/docs/creating-packages/#register).

**Comment by signalpoint** [comment]
@rjsteinert Great idea. I'll get a D7 version wrapped up for bower first. Were you looking for D8?

**Comment by rjcorwin** [comment]
Looking for D7 for the time being. If you need any help, I would be happy
to jump on a hangout. Thanks!

**Comment by signalpoint** [comment]
@rjsteinert I've published jDrupal as `jdrupal` to npmjs and to bower: https://www.npmjs.com/package/jdrupal

You should now be able to run `npm install jdrupal` or `bower install jdrupal`, thanks for the push in the right direction!

**Comment by rjcorwin** [comment]
+1 I just used `bower install jdrupal` :-)
- RJ

Senior Front End Engineer at Isovera, Javascript Ninja, Farm Hacker, Unix
Philosophy for IoT Evangelist
rj@rjsteinert.com
http://rjsteinert.com
http://twitter.com/rjsteinert
http://github.com/rjsteinert

On Thu, Aug 6, 2015 at 8:23 PM, Tyler Frankenstein <notifications@github.com

**Comment by shanejeffers** [comment]
Is there a way to get the D8 version via Bower?

**Comment by signalpoint** [comment]
@shanejeffers To be honest, I haven't used bower since my last interaction with this issue (~2 years ago), so my knowledge of it is very little, and very dated. From what I recall, the `bower.json` file lets you specify a default branch... and I guess I thought bower itself listened to the default branch specified at the repo's location (which in this case is github and the default branch is 8.x-1.x).
