### ISSUE TITLE
/user/login_status should be implemented before actually making attempt to login

### ISSUE THREAD

**Issue by VishalKumarSahu** [signalpoint/jDrupal#90]

**Comment by signalpoint** [comment]
@VishalKumarSahu If I understand correctly, `login_status` was not available when I created this version of the module. Because of that, I created the `connect` resource in jDrupal. The idea was to call `connect` and that would return to you the current authentication status. From there, our apps can decide what to do.

I don't think the user login call should check login status, because I think that should be up to the developer. If `login_status` is now a core resource, I think we could add it as a supported resource in jDrupal. Then one could just call `login_status` and then make a subsequent call to `login`.

**Comment by VishalKumarSahu** [comment]
Yes it depends on developer to use `login_status` or not. It's a good library.
